### ISSUE TITLE
[manualNameChunksPlugin] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AlucardYang** [CaptainLiao/vite-plugin-webpackchunkname#1]
much Chunks will report an error: 
[manualNameChunksPlugin] Maximum call stack size exceeded

**Comment by CaptainLiao** [comment]
Would you please show more detail about the error that help me to fix it?

**Comment by AlucardYang** [comment]
很高兴收到你的邮件~谢谢O(∩_∩)O哈哈~

**Comment by AlucardYang** [comment]
transforming (1198) node_modules\axios\lib\core\createError.jsUse of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
✓ 1209 modules transformed.
[manualNameChunksPlugin] Maximum call stack size exceeded
error during build:
RangeError: Maximum call stack size exceeded
    at getImportersChunkNames (D:\project\insurance\node_modules\vite-plugin-webpackchunkname\dist\vite-plugin-webpackchunkname.js:300:21)
    at getImportersChunkNames (D:\project\insurance\node_modules\vite-plugin-webpackchunkname\dist\vite-plugin-webpackchunkname.js:297:13)
    at getImportersChunkNames (D:\project\insurance\node_modules\vite-plugin-webpackchunkname\dist\vite-plugin-webpackchunkname.js:297:13)
    at getImportersChunkNames (D:\project\insurance\node_modules\vite-plugin-webpackchunkname\dist\vite-plugin-webpackchunkname.js:297:13)
    at getImportersChunkNames (D:\project\insurance\node_modules\vite-plugin-webpackchunkname\dist\vite-plugin-webpackchunkname.js:297:13)
    at getImportersChunkNames (D:\project\insurance\node_modules\vite-plugin-webpackchunkname\dist\vite-plugin-webpackchunkname.js:297:13)
    at getImportersChunkNames (D:\project\insurance\node_modules\vite-plugin-webpackchunkname\dist\vite-plugin-webpackchunkname.js:297:13)
    at getImportersChunkNames (D:\project\insurance\node_modules\vite-plugin-webpackchunkname\dist\vite-plugin-webpackchunkname.js:297:13)
    at getImportersChunkNames (D:\project\insurance\node_modules\vite-plugin-webpackchunkname\dist\vite-plugin-webpackchunkname.js:297:13)
    at getImportersChunkNames (D:\project\insurance\node_modules\vite-plugin-webpackchunkname\dist\vite-plugin-webpackchunkname.js:297:13)

**Comment by CaptainLiao** [comment]
Please update vite-plugin-webpackchunkname 0.0.2 to fix it.

change is here: [fix: Maximum call stack size exceeded](https://github.com/CaptainLiao/vite-plugin-webpackchunkname/commit/c8e3873fbebb6347d7e703a0b3d3f035cea70c9b)

**Comment by AlucardYang** [comment]
很高兴收到你的邮件~谢谢O(∩_∩)O哈哈~
