### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by odirleiborgert** [CaptainLiao/vite-plugin-webpackchunkname#15]
Hi 

This error happens during build: `TypeError: Cannot read property 'alias' of undefined`

```

$ npm run build

> my-project-name@0.0.1 build W:\my-project-name
> vite build

error during build:
TypeError: Cannot read property 'alias' of undefined
    at config (W:\my-project-name\node_modules\vite-plugin-webpackchunkname\dist\vite-plugin-webpackchunkname.js:1:7030)
    at runConfigHook (file:///W:/my-project-name/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:63556:31)
    at resolveConfig (file:///W:/my-project-name/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:63076:20)
    at async doBuild (file:///W:/my-project-name/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:45673:20)
    at async build (file:///W:/my-project-name/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:45662:16)
    at async CAC.<anonymous> (file:///W:/my-project-name/node_modules/vite/dist/node/cli.js:748:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project-name@0.0.1 build: `vite build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project-name@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user-name\AppData\Roaming\npm-cache\_logs\2022-12-16T15_58_42_257Z-debug.log

```

**Comment by CaptainLiao** [comment]
Guess no alias in your `vite.config.ts` file

Patch is here: [`vite-plugin-webpackchunkname@0.2.1`](https://github.com/CaptainLiao/vite-plugin-webpackchunkname/commit/f9c423db9e036a06131bfe0e978910098afffba5)

**Comment by odirleiborgert** [comment]
Thanks @CaptainLiao
